### ISSUE TITLE
Browser version

### ISSUE THREAD

**Issue by Iqwertz** [elrumordelaluz/path-that-svg#6]
Is there a version for only browser use?
I dont want to use yarn or any additional library!

**Comment by elrumordelaluz** [comment]
Hi @Iqwertz, thanks for open the _Issue_.

There is a browser version in the _package_. You could consume or download from [unpkg.com/path-that-svg](https://unpkg.com/path-that-svg@1.2.3/dist/pathThatSvg.umd.js), where `pathThatSvg` is globally available. Here is an [example pen](https://codepen.io/elrumordelaluz/pen/yLNjxMG).
